name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Package
      env:
        CARGO_API_KEY: {{ secrets.CARGO_API_KEY }}
      run: echo $CARGO_API_KEY | cargo publish -
